[theme]
# Fondo principal de la aplicación - gris claro
primaryColor = "#1ed760"  # Color primario para elementos interactivos Verde Spotify
# backgroundColor = "#121212"  # Fondo negro
backgroundColor = "#ffffff"  # Fondo blanco
#secondaryBackgroundColor = "#121212"  # Fondo secundario (sidebars, etc.) - negro
secondaryBackgroundColor = "#ffffff"  # Fondo secundario (sidebars, etc.) - blanco
# textColor = "#ffffff"  # Color de texto principal - blanco
textColor = "#121212"  # Color de texto principal - negro

# Colores específicos para widgets y componentes
font = "sans serif"